# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "0.2"

  on_macos do
    on_intel do
      sha256 "88da20931725abf3ce0f5eaad494cebd80dde8d3f3bbd9a41d49c780d6af7206"
      url "https://github.com/mikker/wt/releases/download/#{version}/wt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "92b6994db899878c2aab50630ddf94af248b0d02cee68330ceb30c8dcc80ee82"
      url "https://github.com/mikker/wt/releases/download/#{version}/wt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "792332a0ea083bda90667f9cb9dd08a59be88c9f5a7988f5a75962c762c07287"
      url "https://github.com/mikker/wt/releases/download/#{version}/wt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff12d34b249f6fa3bb326779603bc1957b1f6981218a8800ec05d50dd8945731"
      url "https://github.com/mikker/wt/releases/download/#{version}/wt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wt"
  desc "Ephemeral Git worktree manager"
  homepage "https://github.com/mikker/wt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wt"]
    end
  end

  # No zap stanza required

end
