# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "0.6"

  on_macos do
    on_intel do
      sha256 "b631da1d5ea58caf62f1b9e8bd8e49483d4b9d0f031433c13b04d6aeac3dd42e"
      url "https://github.com/mikker/wt/releases/download/#{version}/wt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b6228a2e1e3704f9f1db795c0b614d7cc424e99685fdc07a431e4a9e45a7d5aa"
      url "https://github.com/mikker/wt/releases/download/#{version}/wt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7bbe70bc0e2e2bad5ce20c2ac70c1415f53983e2d0555b6c481634088b435d18"
      url "https://github.com/mikker/wt/releases/download/#{version}/wt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "92ef79cf6a0ed787d527b910364ed844efe58dd9ada9443228b05c24345ab0e8"
      url "https://github.com/mikker/wt/releases/download/#{version}/wt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wt"
  desc "Ephemeral Git worktree manager"
  homepage "https://github.com/mikker/wt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wt"]
    end
  end

  # No zap stanza required

end
