# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "0.4"

  on_macos do
    on_intel do
      sha256 "f1fd17914c4f3423927e0cece18a6503e124f284c12a8cd969c089825f0233dd"
      url "https://github.com/mikker/wt/releases/download/#{version}/wt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e3dbc898001be90c0c2450a2e2517aa037781ad10316d749a4b784d0978f11b0"
      url "https://github.com/mikker/wt/releases/download/#{version}/wt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "71653d01d48269efcce3f8d1babae0574e7a787c2dc5ee6d7a4de81aea5b3323"
      url "https://github.com/mikker/wt/releases/download/#{version}/wt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2b2b34ccf8b67c6a95111a4c3f2d33e361d712755035deafeaafd57acc27f4d1"
      url "https://github.com/mikker/wt/releases/download/#{version}/wt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wt"
  desc "Ephemeral Git worktree manager"
  homepage "https://github.com/mikker/wt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wt"]
    end
  end

  # No zap stanza required

end
